websites = {
    "google": "https://www.google.com",
    "youtube": "https://www.youtube.com",
    "facebook": "https://www.facebook.com",
    "twitter": "https://www.twitter.com",
    "instagram": "https://www.instagram.com",
    "linkedin": "https://www.linkedin.com",
    "reddit": "https://www.reddit.com",
    "github": "https://www.github.com",
    "gitlab": "https://www.gitlab.com",
    "bitbucket": "https://www.bitbucket.org",
    "wikipedia": "https://www.wikipedia.org",
    "amazon": "https://www.amazon.com",
    "ebay": "https://www.ebay.com",
    "netflix": "https://www.netflix.com",
    "hulu": "https://www.hulu.com",
    "disney+": "https://www.disneyplus.com",
    "spotify": "https://www.spotify.com",
    "soundcloud": "https://www.soundcloud.com",
    "pandora": "https://www.pandora.com",
    "twitch": "https://www.twitch.tv",
    "tiktok": "https://www.tiktok.com",
    "snapchat": "https://www.snapchat.com",
    "whatsapp": "https://www.whatsapp.com",
    "telegram": "https://www.telegram.org",
    "signal": "https://www.signal.org",
    "zoom": "https://www.zoom.us",
    "skype": "https://www.skype.com",
    "slack": "https://www.slack.com",
    "teams": "https://www.microsoft.com/en-us/microsoft-teams/group-chat-software",
    "asana": "https://www.asana.com",
    "trello": "https://www.trello.com",
    "jira": "https://www.atlassian.com/software/jira",
    "confluence": "https://www.atlassian.com/software/confluence",
    "dropbox": "https://www.dropbox.com",
    "google drive": "https://www.google.com/drive/",
    "onedrive": "https://www.onedrive.com",
    "icloud": "https://www.icloud.com",
    "box": "https://www.box.com",
    "mailchimp": "https://www.mailchimp.com",
    "constant contact": "https://www.constantcontact.com",
    "sendgrid": "https://www.sendgrid.com",
    "shopify": "https://www.shopify.com",
    "woocommerce": "https://www.woocommerce.com",
    "magento": "https://www.magento.com",
    "wix": "https://www.wix.com",
    "squarespace": "https://www.squarespace.com",
    "weebly": "https://www.weebly.com",
    "wordpress": "https://www.wordpress.com",
    "blogger": "https://www.blogger.com",
    "medium": "https://www.medium.com",
    "tumblr": "https://www.tumblr.com",
    "redbubble": "https://www.redbubble.com",
    "etsy": "https://www.etsy.com",
    "craigslist": "https://www.craigslist.org",
    "indeed": "https://www.indeed.com",
    "monster": "https://www.monster.com",
    "glassdoor": "https://www.glassdoor.com",
    "linkedin learning": "https://www.linkedin.com/learning/",
    "coursera": "https://www.coursera.org",
    "udemy": "https://www.udemy.com",
    "khan academy": "https://www.khanacademy.org",
    "edx": "https://www.edx.org",
    "pluralsight": "https://www.pluralsight.com",
    "codecademy": "https://www.codecademy.com",
    "freecodecamp": "https://www.freecodecamp.org",
    "stack overflow": "https://www.stackoverflow.com",
    "quora": "https://www.quora.com",
    "yahoo": "https://www.yahoo.com",
    "bing": "https://www.bing.com",
    "duckduckgo": "https://www.duckduckgo.com",
    "ask.com": "https://www.ask.com",
    "aol": "https://www.aol.com",
    "msn": "https://www.msn.com",
    "cnn": "https://www.cnn.com",
    "bbc": "https://www.bbc.com",
    "the new york times": "https://www.nytimes.com",
    "the guardian": "https://www.theguardian.com",
    "fox news": "https://www.foxnews.com",
    "huffpost": "https://www.huffpost.com",
    "npr": "https://www.npr.org",
    "reuters": "https://www.reuters.com",
    "bloomberg": "https://www.bloomberg.com",
    "forbes": "https://www.forbes.com",
    "business insider": "https://www.businessinsider.com",
    "techcrunch": "https://www.techcrunch.com",
    "wired": "https://www.wired.com",
    "mashable": "https://www.mashable.com",
    "the verge": "https://www.theverge.com",
    "cnet": "https://www.cnet.com",
    "zdnet": "https://www.zdnet.com",
    "gizmodo": "https://www.gizmodo.com",
    "ars technica": "https://www.arstechnica.com",
    "lifehacker": "https://www.lifehacker.com",
}
